app: appDemo
stage: dev

component: django@dev
name: djangoDemo

inputs:
  src:
    # TODO: 安装python项目依赖到项目当前目录
    hook: 'pip3 install -r requirements.txt -t ./'
    dist: ./
    exclude:
      - .env
      - 'requirements/**'
      - '__pycache__/**'
  region: ap-guangzhou
  functionConf:
    projectName: djangodemo
    name: ${name}
    runtime: Python3.6
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
